### PR TITLE
fix panic on metrics and add go.mod

### PR DESCRIPTION
**Pull request by DoubleDi**

### CODE REVIEW

**Comment by xaionaro** [comment]
@wisesoven : JFYI: it looks reasonable, except for a dependency on `reflect2` for one simple function. But I guess it's better than have an error :)

**Comment by DoubleDi** [comment]
reflect2 on that case is 5 times faster than reflect. 
```
BenchmarkReflect2-8   	1000000000	         0.473 ns/op	       0 B/op	       0 allocs/op
BenchmarkReflect-8    	594661417	         1.94 ns/op	       0 B/op	       0 allocs/op
```
And casting to a pointer with unsafe looks unsafe

**Comment by xaionaro** [comment]
@DoubleDi : yeah, it was expected (I've looked into the implementation before leaving that comment) :)

And yes: this definitely should be merged in my humble opinion. But if there's no rush then I would prefer to wait for @wisesoven 's decision.

**Comment by Vintorez** [comment]
@xaionaro thank you for having a look at the PR! I'll merge it

**Pull request merged**
